version: "3.9"
services:
  db:
    container_name: golang-todo-list.db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

networks:
  default:
    name: golang-todo-list-network
    external: true
