version: "3.9"
services:
  api:
    container_name: golang-todo-list.api
    image: golang-todo-list
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
  db:
    container_name: golang-todo-list.db
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      # TODO: Use .env values here
      MYSQL_DATABASE: todo_list
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
