version: "3.9"
services:
  api:
    container_name: golang-todo-list.api
    image: golang-todo-list
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

networks:
  default:
    name: golang-todo-list-network
    external: true
