version: "3.9"
services:
  api:
    container_name: golang-todo-list.api
    image: golang-todo-list
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
